# config file for raft and the kv
# version: '3'
metadata:
  node_name: "ambaco"
services:
  raft:
    listiner_addr: "100.91.203.91:45235"
    connections:
        - "100.91.203.91:45235"
        - "100.102.173.22:45235"
  store:
    local_path: "./tests/"
