# config file for raft and the kv
# version: '3'
metadata:
  node_name: "ambaco"
services:
  raft:
    persist_file: "raft.state"
    listiner_addr: "100.91.203.91:45235"
    connections:
        - "100.91.203.91:45235"
        - "100.91.203.91:23523"
  store:
    local_path: "./store_local/"
